---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kuber
  labels:
    app: hello
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: hello-app
        image:  172.17.0.1:8082/helloworld-nprohorov:rc-32
        ports:
        - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - port: 8080
      targetPort: 8090
      nodePort: 30100
